parkingmanagement/urls.py
from django.contrib import admin
from django.urls import path,include
from users.views import home
urlpatterns = [
    path('',home),
    path('admin/', admin.site.urls),
    path('users/',include('users.urls')),
    path('tariff/',include('tariff.urls')),
    path('carposition/',include('carposition.urls')),
    path('accounts/',include('accountant.urls')),
]

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('home',views.home,name='home'),
    path('Checkoutuser',views.Checkoutuser,name='Checkoutuser'),
    path('login',views.login,name='login'),
    path('register',views.register,name='register'),
    path('logout',views.logout, name= 'logout'),
    path('emptyslot/<slug:username>',views.emptyslot,name='emptyslot'),
    path('user_detail',views.user_detail,name='user_detail'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User


from django.contrib.auth.models import AbstractUser
# Create your models here.
from django.db.models import CharField
class User(AbstractUser):
    is_accountant = models.BooleanField(default=False)
    is_site_manager= models.BooleanField(default=False)

# Create your models here
class UserInfo(models.Model):
    user_name = models.CharField(u'username',max_length=15,default='')
    user_phone =  models.CharField(u'cellphone number',max_length=10,default='')
    car_number = models.CharField(u'Car number plate',max_length=10,default='')
    car_type = models.CharField(u'Model',max_length=11,default='')
    car_booking_status=  models.BooleanField('Booking status',default=False)
    car_site_address = models.CharField(u'Site Number',max_length=20,null=True)
    car_slot_no = models.CharField(u'Slot Number',max_length=20,null=True)
    admin_bit=  models.BooleanField('Admin Bit',default=False)

    def __str__(self):
        return u'%s' % self.car_number
    class Meta:        
        verbose_name = 'User Info'
        verbose_name_plural = 'User Info'

users/forms.py
from django import forms
from django.contrib import auth
from users.models import UserInfo
from django.contrib.auth import get_user_model
User = get_user_model()

class LoginForm(forms.Form):
    username = forms.CharField(label='username', widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'please enter user name'}))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'Enter Password'}))

    def clean(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']

        user = auth.authenticate(username=username, password=password)
        if user is None:
            raise forms.ValidationError('Username or password is incorrect')
        else:
            self.cleaned_data['user'] = user
        return self.cleaned_data

class RegForm(forms.Form):
    username = forms.CharField(label='username',max_length=30,min_length=3,widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Please enter 3-30 usernames'}))
    email = forms.EmailField(label='email', widget=forms.EmailInput(attrs={'class':'form-control', 'placeholder':'email-id'}))
    password = forms.CharField(label='password', min_length=6,widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'password'}))
    password_again = forms.CharField(label='Re-enter password', min_length=6,widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'Password'}))

    def clean_username(self):
        print("inside clean_username")
        username = self.cleaned_data['username']
        print(username)
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('Username already exists')
        print("clean_username completed")
        return username

    def clean_email(self):
        print("inside email")
        email = self.cleaned_data['email']
        print(email)
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('email already exits')

        print("clean_email completed")
        return email

    def clean_password_again(self):
        password = self.cleaned_data['password']
        password_again = self.cleaned_data['password_again']
        if password != password_again:
            raise forms.ValidationError('Inconsistent password entered twice')

        print("clean_password_again completed")

        return password_again

class UserDetailForm(forms.Form):
    # user_name= forms.CharField(label=u'Username ',widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':' Enter your username again'}))
    # user_first_name= forms.CharField(label=u'Name ',widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':' Enter your Name'}))
    user_phone = forms.CharField(label=u'cellphone number',widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':' Phone Number'}))
    car_number = forms.CharField(label=u'number plate',widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Please enter the license plate number'}))
    car_type = forms.CharField(label=u'Model',widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Please enter the model'}))
    # car_color = forms.CharField(label=u'Car color',widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':' enter the car color'}))
    # car_kind = forms.CharField(label=u'car type',widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Please enter the type of vehicle'}))
    # car_company = forms.CharField(label=u'car Company',widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Please enter the Company of vehicle'}))


    def clean(self):
        # user_name= self.cleaned_data['user_name']
        user_phone = self.cleaned_data['user_phone']
        car_number = self.cleaned_data['car_number']
        car_type = self.cleaned_data['car_type']
        # car_color = self.cleaned_data['car_color']
        # car_kind = self.cleaned_data['car_kind']
        # user_first_name= self.cleaned_data['user_first_name']
        # car_company= self.cleaned_data['car_company']
        return self.cleaned_data    
    # def clean_user_phone(self):
    #     user_phone = self.cleaned_data['user_phone']
    #     if UserInfo.objects.filter(user_phone=user_phone).exists():
    #         raise forms.ValidationError('用户名')

users/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from django.contrib import auth
from django.contrib.auth.models import User
from carposition.models import Positions
from users.models import UserInfo
from users.forms import LoginForm, RegForm, UserDetailForm
from django.conf import settings
from tariff.models import Tariffs
from django.views.decorators.cache import cache_control
from django.contrib.auth.decorators import login_required
# import datetime
# import time
# from datetime import datetime, date, time, timedelta

from django.utils import timezone
import datetime
import time
from datetime import datetime, date, time, timedelta
from django.contrib.auth import get_user_model
User = get_user_model()


@cache_control(no_cache=True, must_revalidate=True, no_store=True)


def home(request):
    # print("HI")

    car_positions =Positions.objects.filter(position_status=True)
    car_pos_num = car_positions.count()
    # print(request.user.is_accountant)
    # print(request.user.is_site_manager)
    if request.user.is_authenticated and  not request.user.is_superuser and not request.user.is_accountant and not request.user.is_site_manager :
        print(request.user)
        User_info = UserInfo.objects.get(user_name=request.user)
        print(User_info.car_booking_status)
        print(car_pos_num)
        context = {
        'User_info': User_info,
        'car_pos_num' : car_pos_num,
        }
    else:
        context = {
            'car_pos_num' : car_pos_num
    }
    print("Rendering home")   
    return render(request,'home.html',context)

def login(request):
    if request.method == 'POST':
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            user = login_form.cleaned_data['user']
            auth.login(request, user)
            return redirect(request.GET.get('from', reverse('home')))
    else:
        login_form = LoginForm()
    context = {}
    context['login_form'] = login_form
    return render(request, 'login.html', context)

def register(request):
    if request.method == 'POST':
        reg_form = RegForm(request.POST)
        print("Hello ")
        if reg_form.is_valid():
            print("Hello")
            username = reg_form.cleaned_data['username']
            email = reg_form.cleaned_data['email']
            password = reg_form.cleaned_data['password']
            # Create user
           
            user = User.objects.create_user(username, email, password)
            print(user.username)
            user.save()
            # Login user

            user = auth.authenticate(username=username, password=password)
            auth.login(request, user)
            
            return redirect(request.GET.get('from', reverse('user_detail')))
        print("This place reached " + str(reg_form.errors))
    else:
        reg_form = RegForm()
    context = {}
    context['reg_form'] = reg_form
    return render(request, 'register.html', context)

@login_required
def user_detail(request):
    if request.method =='POST':
        user_form = UserDetailForm(request.POST)
        if user_form.is_valid() and (request.user is not None):
            # Add user information
            # print("Hello")
            user_info = UserInfo()
            # print("Hi")
            user_info.user_name = request.user.username
            # user_info.user_name = user_form.cleaned_data['user_name']
            # user_info.user_first_name= user_form.cleaned_data['user_first_name']
            user_info.user_phone = user_form.cleaned_data['user_phone']
            user_info.car_number = user_form.cleaned_data['car_number']
            user_info.car_type = user_form.cleaned_data['car_type']
            # user_info.car_color = user_form.cleaned_data['car_color']
            # user_info.car_kind = user_form.cleaned_data['car_kind']
            user_info.save()
        return redirect(request.GET.get('from', reverse('home')))
    else:
        user_form = UserDetailForm()
    context = {}
    context['user_form'] = user_form
    return render(request,'user_detail.html',context)


@login_required
def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(settings.LOGIN_URL)

def Checkoutuser(request):
    if not request.user.is_site_manager:
        return redirect('/users/home')

    UserInfolist = UserInfo.objects.values()

    # print(UserInfolist)
    context={
        'UserInfolist':UserInfolist
    }

    return render(request,'Checkoutuser.html',context)


def emptyslot(request,username):
    if request.user.is_site_manager:
        return redirect('/users/home')

    print(username)
    UserInfoobject = UserInfo.objects.get(user_name= username)
    UserInfoobject.admin_bit= True
    UserInfoobject.car_booking_status=False
    Tariffobject= Tariffs.objects.get(user_name=username)
    Tariffobject.end_time = datetime.now()

    print(datetime.now())
    print(Tariffobject.start_time)
    print(Tariffobject.end_time)
    Positionobject= Positions.objects.get(position_num =Tariffobject.postion_no)
    Positionobject.position_status=True
    '''    if(hoursspent>1):
        query.parking_money=hoursspent*query.per_hour_money
    else:
        query.parking_money=query.per_hour_money
    
    query.parking_time = hoursspent
    query.save()'''
    print(Tariffobject.start_time.hour)
    print(Tariffobject.end_time.hour)
    st_sec = Tariffobject.start_time.second + Tariffobject.start_time.minute*60 + Tariffobject.start_time.hour*24*60
    et_sec = Tariffobject.end_time.second+ Tariffobject.end_time.minute*60 + Tariffobject.end_time.hour*24*60
    hoursspent = (et_sec-st_sec)
    print(hoursspent)
    hoursspent = hoursspent//3600
    print(st_sec)
    print(et_sec)
    print(hoursspent)
    if(hoursspent>1):
        # hoursspent=hoursspent*Tariffobject.per_hour_money
        Tariffobject.parking_money= hoursspent*Tariffobject.per_hour_money
    else:
        Tariffobject.parking_money=Tariffobject.per_hour_money
    print(hoursspent)
    Tariffobject.parking_time = hoursspent
    Positionobject.save()
    UserInfoobject.save()
    Tariffobject.save()
    context= {
        'tariffobject':Tariffobject,
    }
    return render(request,'emptyslot.html',context)

users/templates/Checkoutuser.html
{% extends 'base.html' %}

{% block title %}
Parking system|Home
{% endblock %}
{% load staticfiles %}
{% block content %}

    <div id="sitebg" style="width:100%;height: 110%; text-align: center;margin: 0 auto;position: absolute;"></div>
    <div>
        <div id="windows1">
            <div style="height: 50px;"></div>
            <div id="loginbox" style=" border: 1px solid #f1f1f1;background-color: rgba(0,0,0, 0.4); padding: 20px;">
                   
                <h1  style="color:white ; margin-bottom: 50px;"> Choose the user you want to vacate </h1>
                   <!-- {% for rate in rates %}
                   <h4>  {{ rate.pay_per_time }}</h4>
                    {% endfor %} -->
                <table class="table">
                        <thead>                        
                                <i class="fas fa-warehouse" style="font-size: 50px; color: white ;float : left ; padding-bottom: 20px;padding-left: 170px;"></i>
                                <i class="fas fa-dollar-sign" style="font-size: 50px; color: white ;float : right ; padding-bottom: 20px;padding-right: 210px;"></i>
                        </thead>
                        <tbody>
    
                            {% for userobject in UserInfolist  %}
                            {% if  userobject.car_booking_status %}
                            <tr>

                                
                                <td>                    
                                    <h4 style="color:white ; float: right ; padding-right: 150px;">  Username</h4>
                                </td>
                                <td>
                                    <h4 style="padding-left: 150px; color:white"> <a href="emptyslot/{{userobject.user_name}}" style="color: orangered;"> {{ userobject.user_name }} </a>   </h4>
                                </td>
                            </tr>
                            {% endif %}
                            {% endfor %}
                        </tbody>
                </table>                    
            </div>        
        </div>            
    </div>







<!-- 
    {% for userobject in UserInfolist  %}
        <h4>        
         {% if  userobject.car_booking_status %}       {{ userobject.user_name }}   ---- {{ userobject.car_booking_status }}---{{ userobject.car_site_address }}
            ---{{ userobject.car_slot_no }}
           <a href="emptyslot/{{userobject.user_name}}"> {{ userobject.user_name }} </a>  {% endif %} </h4>
                 -->
    <!-- {% for user in userobject %} car_site_address = models.CharField(u'Site Number',null=True)
    car_slot_no -->





    <!-- {% endfor %} 
    
    -->
    {% endfor %}

{% endblock %}

users/templates/accounts_index.html
{% extends 'base.html' %}

{% block title %}
Parking system|
{% endblock %}
{% load staticfiles %}
{% block content %}
<div id="sitebg" style="width:100%;height: 110%; text-align: center;margin: 0 auto;position: absolute;"></div>
<div>
    <div id="windows1">
        <div style="height: 50px;"></div>
        <div id="loginbox" style=" border: 1px solid #f1f1f1;background-color: rgba(0,0,0, 0.4); padding: 20px;">
            <h1  style="color:white ; margin-bottom: 50px;"> Today's total collection : Rs. {{totalamount}} </h1>
 
            <h1  style="color:white ; margin-bottom: 50px;"> Revenue per Site </h1>
               <!-- {% for rate in rates %}
               <h4>  {{ rate.pay_per_time }}</h4>
                {% endfor %} -->
            <table class="table">
                    <thead>                        
                            <i class="fas fa-warehouse" style="font-size: 50px; color: white ;float : left ; padding-bottom: 20px;padding-left: 170px;"></i>
                            <i class="fas fa-dollar-sign" style="font-size: 50px; color: white ;float : right ; padding-bottom: 20px;padding-right: 210px;"></i>
                    </thead>
                    <tbody>

                        {% for object in tariffobject %}
                        <tr>
                            <td>
                                <h4 style="padding-left: 150px; "> <a style="color:white" > {{ object.site_address}}</a>   </h4>
                            </td>
                            
                            <td>                    
                                <h4 style="color:white ; float: right ; padding-right: 150px;">  Rs. {{ object.parking_money }}</h4>
                            </td>
                        </tr>
                        
                        {% endfor %}

                    </tbody>
            </table>                    
        </div>        
    </div>            
</div>

<!-- <div id="templatemo_banner_slide" class="container_wapper">
    <div class="camera_wrap camera_emboss" id="camera_slide">
        <div data-src="{% static '/login/images/banner_slide_01.jpg' %}"></div>
        <div data-src="{% static '/login/images/banner_slide_02.jpg'  %}"></div>
        <div data-src="{% static '/login/images/banner_slide_03.jpg'  %}"></div>
        <div data-src="{% static '/login/images/banner_slide_04.jpg'  %}"></div>
        <div data-src="{% static '/login/images/banner_slide_05.jpg'  %}"></div>
    </div>
</div> -->

{% endblock %}

users/templates/bills.html
{% extends 'base.html' %}

{% block title %}
Parking system|Home
{% endblock %}
{% load staticfiles %}
{% block content %}

  <div id="sitebg" style="width:100%;height: 110%; text-align: center;margin: 0 auto;position: absolute;"></div>
  <div>
      <div id="windows1">
          <div style="height: 50px;"></div>
          <div id="loginbox" style=" border: 1px solid #f1f1f1;background-color: rgba(0,0,0, 0.4); padding: 20px;">
                 
              <h1  style="color:white ; margin-bottom: 50px;">Your Billing Status is:</h1>
                 <!-- {% for rate in rates %}
                 <h4>  {{ rate.pay_per_time }}</h4>
                  {% endfor %} -->
              <table class="table">
                      <thead>                        
                              <i class="fas fa-warehouse" style="font-size: 50px; color: white ;float : left ; padding-bottom: 20px;padding-left: 170px;"></i>
                              <i class="fas fa-dollar-sign" style="font-size: 50px; color: white ;float : right ; padding-bottom: 20px;padding-right: 210px;"></i>
                      </thead>
                      <tbody>
  
                         
                          <tr>

                              
                              <td>                    
                                  <h4 style="color:white ; float: right ; padding-right: 150px;">  Username</h4>
                              </td>
                              <td>
                                  <h4 style="padding-left: 150px; color:white">{{ query.user_name }}   </h4>
                              </td>
                          </tr>

                          <tr>

                              
                              <td>                    
                                  <h4 style="color:white ; float: right ; padding-right: 150px;">  Car Plate Number</h4>
                              </td>
                              <td>
                                  <h4 style="padding-left: 150px; color:white"> {{ query.car_number }}</h4> 
                              </td>
                          </tr>

                          <tr>

                              
                              <td>                    
                                  <h4 style="color:white ; float: right ; padding-right: 150px;">  In-Time</h4>
                              </td>
                              <td>
                                  <h4 style="padding-left: 150px; color:white"> {{ query.start_time }}</h4> 
                              </td>
                          </tr>

                          <tr>

                              
                              <td>                    
                                  <h4 style="color:white ; float: right ; padding-right: 150px;">  Current-Time</h4>
                              </td>
                              <td>
                                  <h4 style="padding-left: 150px; color:white"> {{ query.end_time }}</h4> 
                              </td>
                          </tr>

                          <tr>

                              
                              <td>                    
                                  <h4 style="color:white ; float: right ; padding-right: 150px;"> Parking Site Address</h4>
                              </td>
                              <td>
                                  <h4 style="padding-left: 150px; color:white"> {{ query.site_address }}</h4> 
                              </td>
                          </tr>
                          
                          <tr>

                              
                              <td>                    
                                  <h4 style="color:white ; float: right ; padding-right: 150px;">  Parking Time(hrs)</h4>
                              </td>
                              <td>
                                  <h4 style="padding-left: 150px; color:white"> {{ query.parking_time }}</h4> 
                              </td>
                          </tr>
                          <tr>

                              
                              <td>                    
                                  <h4 style="color:white ; float: right ; padding-right: 150px;"> Per Hour Charge</h4>
                              </td>
                              <td>
                                  <h4 style="padding-left: 150px; color:white"> {{ query.per_hour_money }}</h4> 
                              </td>
                          </tr>
                          
                          <tr>

                              
                              <td>                    
                                  <h4 style="color:white ; float: right ; padding-right: 150px;">  Total Charge</h4>
                              </td>
                              <td>
                                  <h4 style="padding-left: 150px; color:white"> {{ query.parking_money }}</h4> 
                              </td>
                          </tr>
                      </tbody>
              </table>                    
          </div>        
      </div>            
  </div>
<!-- 
    <table class="table">
            <thead>                        
            </thead>
            <tbody>
                <tr>
                    
                    <td>                    </td>
                    
                    <td>                    
                        <h4 >  {{ query.user_name }}</h4>
                        <h4 >  {{ query.car_number }}</h4>
                        <h4 >  {{ query.start_time }}</h4>
                        <h4 >  {{ query.end_time }}</h4>
                        <!-- <h4 >  {{ query.ticket_type }}</h4> -->
                       <!-- <h4 >  {{ query.parking_time }}</h4>

                        <h4 >  {{ query.parking_money }}</h4>
                        <h4 >  {{ query.per_hour_money }}</h4>


                    </td>
                </tr>
                
                    
            </tbody>
    </table>           -->


{% endblock %}

users/templates/register.html
{% extends 'base.html' %}

{% block title %}
Parking system|Register
{% endblock %}
{% load staticfiles %}
{% block content %}
<div  id="regbg" style="width:100%;height: 100%;text-align: center;margin: 0 auto;position: absolute;"></div>
<div>
<div id="windows1">
     <div style="height: 40px;"></div>
<div id="loginbox" >
            {% if form.errors %}
            <p>Your username or email or car number is already taken. Please try again.</p>
          {% endif %}
        
        <form action="" method="post" name="RegForm" id="RegForm">
            <!-- {% csrf_token %} -->
            {% csrf_token %}
            <div class="control-group normal_text">					
                <h3 style="text-align:center";style="font-family:verdana;color:white;font-size:40px;">
                    Fill out the form and Register
                </h3>

            </div>
            <div style="height: 10px;"></div>
            <div class="control-group">
                <div class="controls">
                    <div class="main_input_box">
                        <span class="add-on bg_lg">
                        <i><img height="37" src="{% static '/login/user.png' %}" /></i>
                        </span><input type="text" name="username" required id="id_username" id="loginname" value="" placeholder="Please type in your name" />
                    </div>
                </div>
            </div>
            <div class="control-group">
                    <div class="controls">
                        <div class="main_input_box">
                            <span class="add-on bg_lg">
                            <i><img height="37" src="{% static '/login/user.png' %}" /></i>
                            </span><input type="email" name="email"  required required id="id_email" id="id_email" value="" placeholder="please input your email" />
                        </div>
                    </div>
                </div>
                <!-- <div class="control-group">
                        <div class="controls">
                            <div class="main_input_box">
                                <span class="add-on bg_ly">
                                <i><img height="37" src="{% static '/login/suo.png' %}" /></i>
                                </span><input type="text" name="idcar" required id="idcar" id="loginname" placeholder="Please enter your Car ID card" class="keypad" keypadMode="full" allowKeyboard="true" value=""/>
                            </div>
                        </div>
                </div> -->
            <div class="control-group">
                <div class="controls">
                    <div class="main_input_box">
                        <span class="add-on bg_ly">
                        <i><img height="37" src="{% static '/login/suo.png' %}" /></i>
                        </span><input type="password" name="password" required id="id_password" id="password" placeholder="Please enter your password" class="keypad" keypadMode="full" allowKeyboard="true" value=""/>
                    </div>
                </div>
            </div>
            <div class="control-group">
                    <div class="controls">
                        <div class="main_input_box">
                            <span class="add-on bg_ly">
                            <i><img height="37" src="{% static '/login/suo.png' %}" /></i>
                            </span><input type="password" name="password_again" id="id_password_again" required placeholder="Enter the password again" class="keypad" keypadMode="full" allowKeyboard="true" value=""/>
                        </div>
                    </div>
                </div>
            
            <div style="float:right;padding-right:10%;position: relative; top: -5px;">
                <div style="float: left;margin-top:3px;margin-right:2px;">
                    <font color="white">Remember password</font>
                </div>
                <div style="float: left;">
                    <input name="form-field-checkbox" id="saveid" type="checkbox"
                        onclick="savePaw();" style="padding-top:0px;" />
                </div>
            </div>
            <div style="height: 20px;"></div>
            <div class="form-actions">
                <div style="width:86%; padding-left: 40px; ">                    
                    <span style="height: 20px; width: 70px;"><input onclick="severCheck();" class="flip-link btn btn-info" id="to-recover" type="submit" value="Register"></span>
                </div>
            </div>
        </form>
    </div>
    </div>
    
    
    
</div>

<!-- <form action="" method="POST">
    {% csrf_token %}
    {% for field in login_form %}
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{ field }}
        <p>{{ field.errors.as_text }}</p>
    {% endfor %}
    <span>{{ login_form.non_field_errors }}</span>
    <input type="submit" value="登录">
</form> -->
{% endblock %}

users/templates/user_detail.html
{% extends 'base.html' %}

{% block title %}
Parking system|User Profile
{% endblock %}
{% load staticfiles %}
{% block content %}

<div  id="loginbg" style="width:100%;height: 100%;text-align: center;margin: 0 auto;position: absolute;">
</div>
<div style="height: 90px;"></div>
<div>
    <div id="windows1">
    <div id="loginbox" >
    		<form action="" method="POST" style="padding: 10px; color: white">
    			<div style="text-align: center; color: white ; margin-bottom: 30px;" > <h3>Welcome {{ user.username}}, fill out this information to complete the registration process</h3></div>
		    {% csrf_token %}
		    {% for field in user_form %}
		    <div style="padding-left: 100px;">
		    	<div style="display: inline; float: left; width: 200px; text-align: right;">
		    		<label style="display: inline;" for="{{ field.id_for_label }}">{{ field.label }}</label>
		    	</div>
		    	<div style="display: inline; position: relative; left: -70px;">
		    		{{ field }}
		    	</div>
		        <p >{{ field.errors.as_text }}</p>
		    </div>
		        
		    {% endfor %}
		    <span>{{ user_form.non_field_errors }}</span>
		    <input type="submit" value="register">
		</form>
		
	</div>
	</div>
</div>
{% endblock %}