carposition/urls.py
from django.urls import path,include
from . import views

urlpatterns = [
    path('index/',views.car_site_index,name='car_site_index'),
    path('book/<int:site_no>',views.site_position_book, name='site_position_book'),
    path('check/<int:site_no>',views.admin_position, name='admin_position'),
    path('order_position/<int:site_no>/<posi_num>',views.order_position,name='order_position'),
    path('download',views.download_positions,name='download'),
    path('admins',views.admins,name='download'),
]

parkingmanagement/urls.py
from django.contrib import admin
from django.urls import path,include
from users.views import home
urlpatterns = [
    path('',home),
    path('admin/', admin.site.urls),
    path('users/',include('users.urls')),
    path('tariff/',include('tariff.urls')),
    path('carposition/',include('carposition.urls')),
    path('accounts/',include('accountant.urls')),
]

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('home',views.home,name='home'),
    path('Checkoutuser',views.Checkoutuser,name='Checkoutuser'),
    path('login',views.login,name='login'),
    path('register',views.register,name='register'),
    path('logout',views.logout, name= 'logout'),
    path('emptyslot/<slug:username>',views.emptyslot,name='emptyslot'),
    path('user_detail',views.user_detail,name='user_detail'),
]

carposition/models.py
from django.db import models

# Create your models here.
class Site(models.Model):
    site_no= models.IntegerField(u'site number',default=0,primary_key=True)
    site_address=models.CharField(max_length=200,default='Mangalore')
    pay_per_time=models.FloatField(u'cost',default='15.0')
    max_capacity=models.IntegerField(u'Capacity',default=0)

    def __str__(self):
      return self.site_address


class Positions(models.Model):
    site_no= models.ForeignKey(Site, on_delete=models.CASCADE)
    position_num = models.CharField('Parking number',max_length=20,default='')
    position_status = models.BooleanField('Parking status [default is unoccupied]',default=True)
    def __str__(self):
      return self.position_num

    class Meta:
        verbose_name = 'Positions'
        verbose_name_plural = 'Positions'
    

carposition/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Site,Positions
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from users.models import UserInfo
from tariff.models import Tariffs,Tickets,Rates
import time
import random
from djqscsv import render_to_csv_response
from django.shortcuts import redirect
from django.conf import settings
import time
from datetime import datetime, date, time, timedelta

# Create your views here.
from django.contrib.auth import get_user_model
User = get_user_model()


def car_site_index(request):#,site_num):
    # site_no = get_object_or_404(Site, site_num=site_num)
    if not request.user.is_authenticated:
        return redirect('/users/home')
    rates= Rates.objects.filter()
    positions_list = Site.objects.filter()#(position_status=True)
    # for rate in rates:
    #     print(rate.pay_per_time)
    zipped_data=zip(positions_list, rates)
    context = {
        'rates': rates,
        'positions_list':positions_list,
        'zipped_data':zipped_data
    }
    return render(request,'car_site_index.html',context)

def site_position_book(request,site_no):
    # status_list = Positions.objects.get(site_no=site_no)
    if not request.user.is_authenticated:
        return redirect('/users/home')
    positions_list = Site.objects.filter(site_no=site_no)# and status_list.site_no=site_no and status_list.position_status=True )
    # site_name= Site.objects.filter(site_no=site_no).site_address
    context = {
        'site_no':site_no,
        # 'site_name':site_name
    }

    # print(positions_list)
    context['positions_list']=positions_list
    return render(request,'car_posi_index.html',context)



def download_positions(request):
    if not request.user.is_superuser :
        return redirect('/users/home')

    qs = Site.objects.all()    
    return render_to_csv_response(qs,filename=u'slots.csv')

def order_position(request,site_no,posi_num):
    if not request.user.is_authenticated:
        return redirect('/users/home')

    position_object=Positions.objects.get(site_no=site_no, position_num = posi_num)
    position_object.position_status = False
    position_object.save()

    Siteobject = Site.objects.get(site_no=site_no)
    user_info = User.objects.get(username=request.user) #Get user information
    ticket = Tickets.objects.order_by('-per_hour_money')
    tariff = Tariffs()
    tariff.user_name = request.user
    
    UserInfoInstance = UserInfo.objects.get(user_name=user_info)
    # print(UserInfoInstance.car_number)
    UserInfoInstance.car_booking_status = True
    UserInfo.admin_bit=False
    UserInfoInstance.car_site_address = Siteobject.site_address
    UserInfoInstance.car_slot_no = position_object.position_num

    # print(UserInfoInstance.car_booking_status)
    UserInfoInstance.save()
    
    tariff.car_number = UserInfoInstance.car_number
    tariff.ticket_type = 'Hour'
    tariff.start_time= datetime.now()
    tariff.end_time= datetime.now()

    # print(datetime.now())
    # print(tariff.start_time)
    tariff.parking_time = 0
    tariff.site_address = Siteobject.site_address
    tariff.postion_no=position_object.position_num
    tariff.per_hour_money = Siteobject.pay_per_time
    tariff.parking_money= tariff.per_hour_money
    # print(tariff.per_hour_money)
 
    tariff.save()       

    return render(request , 'bocked.html')


def admins(request):
    if not (request.user.is_superuser or request.user.is_site_manager):
        return redirect('/users/home')
    rates= Rates.objects.filter()
    positions_list = Site.objects.filter()#(position_status=True)
    # for rate in rates:
    #     print(rate.pay_per_time)
    zipped_data=zip(positions_list, rates)
    context = {
        'rates': rates,
        'positions_list':positions_list,
        'zipped_data':zipped_data
    }
    return render(request,'car_site_index_admin.html',context)

def admin_position(request,site_no):
    if not (request.user.is_superuser or request.user.is_site_manager):
        return redirect('/users/home')

    positions_list = Site.objects.filter(site_no=site_no)# and status_list.site_no=site_no and status_list.position_status=True )
    # site_name= Site.objects.filter(site_no=site_no).site_address
    context = {
        'site_no':site_no,
        # 'site_name':site_name
    }

    # print(positions_list)
    context['positions_list']=positions_list
    return render(request,'car_posi_index_admin.html',context)

carposition/templates/bocked.html
{% extends 'base.html' %}

{% block title %}
Parking system|
{% endblock %}
{% load staticfiles %}
{% block content %}
	
	<script type="text/javascript">
		alert("Your site is booked!")
	</script>

	<div style="text-align: center; margin-top: 150px;">
		<h2>
			Go to our Home Page. <a href="/users/home">Home</a>
		</h2>
		
	</div>


{% endblock %}

carposition/templates/car_posi_index.html
{% extends 'base.html' %}

{% block title %}
Parking system|
{% endblock %}
{% load staticfiles %}
{% block content %}

<div  id="posbg" style="width:100%;height: 100%; text-align: center;margin: 0 auto;position: absolute;"></div>
<div>
        <div id="loginbox">
            {% for item in positions_list %}

                <div style="padding: 20px; background: rgba(0,0,0, 0.4); border: 3px solid #f1f1f1; margin-top: 40px; margin-bottom: 10px;">
                    <h1 style="color:white"> {{ item.site_address}} </h1>
                    <h3 style="color:white"> Choose the desired position</h3>
                </div>
                
                               
                <form action="" method="POST">
                    {% csrf_token %}
                        <div class="grid-container">
                            {% for choice in item.positions_set.all %}
                            
                                {% if choice.position_status    %} 
                                        <div class="grid-item">
                                            <div style="font-size:50px; color: white; position: relative;top: 8px;" >
                                                <i class="fas fa-car"></i>
                                            </div>
                                            <h4 > <a style="color:white" href="/carposition/order_position/{{ item.site_no}}/{{  choice.position_num }}"> {{ choice.position_num}}</a></h4>
                                        </div>
                                        
                                {% else %}
                                        <div class="grid-item">
                                              <div style="font-size:50px;position: relative;top: 8px;">
                                                <i class="fas fa-car"></i>
                                            </div>
                                              <h4>{{ choice.position_num }}</h4>  
                                        </div>
                                            

                                {% endif %}

                            {% endfor %}
                        </div>
                            

                        
                    <span>{{ user_form.non_field_errors }}</span>
                </form>
            {% endfor %}
        </div>        
    </div>            
</div>

{% endblock %}




       
                <!-- {% for item in site_position.Position_set.all %}
                
                    <h4 > <a style="color:white" href="#"> {{ item.position_num}}</a> </h4>
               <h1>efefef</h1>
                {% endfor %} -->
 



       

carposition/templates/car_posi_index_admin.html
{% extends 'base.html' %}

{% block title %}
Parking system|
{% endblock %}
{% load staticfiles %}
{% block content %}

<div  id="posbg" style="width:100%;height: 100%; text-align: center;margin: 0 auto;position: absolute;"></div>
<div>
        <div id="loginbox">
            {% for item in positions_list %}

                <div style="padding: 20px; background: rgba(0,0,0, 0.4); border: 3px solid #f1f1f1; margin-top: 40px; margin-bottom: 10px;">
                    <h1 style="color:white"> {{ item.site_address}} </h1>
                    <h3 style="color:white"> Overview of the Parking Lot Site </h3>
                </div>
                
                               
                <form action="" method="POST">
                    {% csrf_token %}
                        <div class="grid-container">
                            {% for choice in item.positions_set.all %}
                            
                                {% if choice.position_status    %} 
                                        <div class="grid-item">
                                            <div style="font-size:50px; color: white; position: relative;top: 8px;" >
                                                <i class="fas fa-car"></i>
                                            </div>
                                            <h4 >  {{ choice.position_num}}</a></h4>
                                        </div>
                                        
                                {% else %}
                                        <div class="grid-item">
                                              <div style="font-size:50px;position: relative;top: 8px;">
                                                <i class="fas fa-car"></i>
                                            </div>
                                              <h4>{{ choice.position_num }}</h4>  
                                        </div>
                                            

                                {% endif %}

                            {% endfor %}
                        </div>
                            

                        
                    <span>{{ user_form.non_field_errors }}</span>
                </form>
            {% endfor %}
        </div>        
    </div>            
</div>

{% endblock %}




       
                <!-- {% for item in site_position.Position_set.all %}
                
                    <h4 > <a style="color:white" href="#"> {{ item.position_num}}</a> </h4>
               <h1>efefef</h1>
                {% endfor %} -->
 



       

carposition/templates/car_site_index.html
{% extends 'base.html' %}

{% block title %}
Parking system|
{% endblock %}
{% load staticfiles %}
{% block content %}
<div id="sitebg" style="width:100%;height: 110%; text-align: center;margin: 0 auto;position: absolute;"></div>
<div>
    <div id="windows1">
        <div style="height: 50px;"></div>
        <div id="loginbox" style=" border: 1px solid #f1f1f1;background-color: rgba(0,0,0, 0.4); padding: 20px;">
               
            <h1  style="color:white ; margin-bottom: 50px;"> Choose the site nearest to you </h1>
               <!-- {% for rate in rates %}
               <h4>  {{ rate.pay_per_time }}</h4>
                {% endfor %} -->
            <table class="table">
                    <thead>                        
                            <i class="fas fa-warehouse" style="font-size: 50px; color: white ;float : left ; padding-bottom: 20px;padding-left: 170px;"></i>
                            <i class="fas fa-dollar-sign" style="font-size: 50px; color: white ;float : right ; padding-bottom: 20px;padding-right: 210px;"></i>
                    </thead>
                    <tbody>

                        {% for item,rate in zipped_data %}
                        <tr>
                            <td>
                                <h4 style="padding-left: 150px; "> <a style="color:white" href="/carposition/book/{{ item.pk }}"> {{ item.site_address}}</a>   </h4>
                            </td>
                            
                            <td>                    
                                <h4 style="color:white ; float: right ; padding-right: 150px;">  Rs. {{ rate.pay_per_time }}/hour</h4>
                            </td>
                        </tr>
                        
                        {% endfor %}
                    </tbody>
            </table>                    
        </div>        
    </div>            
</div>

<!-- <div id="templatemo_banner_slide" class="container_wapper">
    <div class="camera_wrap camera_emboss" id="camera_slide">
        <div data-src="{% static '/login/images/banner_slide_01.jpg' %}"></div>
        <div data-src="{% static '/login/images/banner_slide_02.jpg'  %}"></div>
        <div data-src="{% static '/login/images/banner_slide_03.jpg'  %}"></div>
        <div data-src="{% static '/login/images/banner_slide_04.jpg'  %}"></div>
        <div data-src="{% static '/login/images/banner_slide_05.jpg'  %}"></div>
    </div>
</div> -->

{% endblock %}

carposition/templates/car_site_index_admin.html
{% extends 'base.html' %}

{% block title %}
Parking system|
{% endblock %}
{% load staticfiles %}
{% block content %}
<div id="sitebg" style="width:100%;height: 110%; text-align: center;margin: 0 auto;position: absolute;"></div>
<div>
    <div id="windows1">
        <div style="height: 50px;"></div>
        <div id="loginbox" style=" border: 1px solid #f1f1f1;background-color: rgba(0,0,0, 0.4); padding: 20px;">
               
            <h1  style="color:white ; margin-bottom: 50px;"> Site Lists </h1>
               <!-- {% for rate in rates %}
               <h4>  {{ rate.pay_per_time }}</h4>
                {% endfor %} -->
            <table class="table">
                    <thead>                        
                            <i class="fas fa-warehouse" style="font-size: 50px; color: white ;float : left ; padding-bottom: 20px;padding-left: 170px;"></i>
                            <i class="fas fa-dollar-sign" style="font-size: 50px; color: white ;float : right ; padding-bottom: 20px;padding-right: 210px;"></i>
                    </thead>
                    <tbody>

                        {% for item,rate in zipped_data %}
                        <tr>
                            <td>
                                <h4 style="padding-left: 150px; "> <a style="color:white" href="/carposition/check/{{ item.pk }}"> {{ item.site_address}}</a>   </h4>
                            </td>
                            
                            <td>                    
                                <h4 style="color:white ; float: right ; padding-right: 150px;">  Rs. {{ rate.pay_per_time }}/hour</h4>
                            </td>
                        </tr>
                        
                        {% endfor %}
                    </tbody>
            </table>                    
        </div>        
    </div>            
</div>

<!-- <div id="templatemo_banner_slide" class="container_wapper">
    <div class="camera_wrap camera_emboss" id="camera_slide">
        <div data-src="{% static '/login/images/banner_slide_01.jpg' %}"></div>
        <div data-src="{% static '/login/images/banner_slide_02.jpg'  %}"></div>
        <div data-src="{% static '/login/images/banner_slide_03.jpg'  %}"></div>
        <div data-src="{% static '/login/images/banner_slide_04.jpg'  %}"></div>
        <div data-src="{% static '/login/images/banner_slide_05.jpg'  %}"></div>
    </div>
</div> -->

{% endblock %}